global:
  security:
    allowInsecureImages: true

sentinel:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/redis-sentinel
    tag: "8.2.1"

replica:
  replicaCount: 3

auth:
  enabled: false

image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: "8.2.1"
